# mappings.py

countries = {
    1: "Afghanistan",
    2: "Albania",
    3: "Algeria",
    4: "Andorra",
    5: "Angola",
    6: "Antigua and Barbuda",
    7: "Argentina",
    8: "Armenia",
    9: "Australia",
    10: "Austria",
    11: "Azerbaijan",
    12: "Bahamas",
    13: "Bahrain",
    14: "Bangladesh",
    15: "Barbados",
    16: "Belarus",
    17: "Belgium",
    18: "Belize",
    19: "Benin",
    20: "Bhutan",
    21: "Bolivia",
    22: "Bosnia and Herzegovina",
    23: "Botswana",
    24: "Brazil",
    25: "Brunei Darussalam",
    26: "Bulgaria",
    27: "Burkina Faso",
    28: "Burundi",
    29: "Cambodia",
    30: "Cameroon",
    31: "Canada",
    32: "Cape Verde",
    33: "Central African Republic",
    34: "Chad",
    35: "Chile",
    36: "China",
    37: "Colombia",
    38: "Comoros",
    39: "Congo, Republic of the...",
    40: "Costa Rica",
    41: "Côte d'Ivoire",
    42: "Croatia",
    43: "Cuba",
    44: "Cyprus",
    45: "Czech Republic",
    46: "Democratic Republic of the Congo",
    47: "Denmark",
    48: "Djibouti",
    49: "Dominica",
    50: "Dominican Republic",
    51: "Ecuador",
    52: "Egypt",
    53: "El Salvador",
    54: "Equatorial Guinea",
    55: "Eritrea",
    56: "Estonia",
    57: "Ethiopia",
    58: "Fiji",
    59: "Finland",
    60: "France",
    61: "Gabon",
    62: "Gambia",
    63: "Georgia",
    64: "Germany",
    65: "Ghana",
    66: "Greece",
    67: "Grenada",
    68: "Guatemala",
    69: "Guinea",
    70: "Guinea-Bissau",
    71: "Guyana",
    72: "Haiti",
    73: "Honduras",
    74: "Hong Kong (S.A.R.)",
    75: "Hungary",
    76: "Iceland",
    77: "India",
    78: "Indonesia",
    79: "Iran",
    80: "Iraq",
    81: "Ireland",
    82: "Israel",
    83: "Italy",
    84: "Jamaica",
    85: "Japan",
    86: "Jordan",
    87: "Kazakhstan",
    88: "Kenya",
    89: "Kiribati",
    90: "Kuwait",
    91: "Kyrgyzstan",
    92: "Lao People's Democratic Republic",
    93: "Latvia",
    94: "Lebanon",
    95: "Lesotho",
    96: "Liberia",
    97: "Libyan Arab Jamahiriya",
    98: "Liechtenstein",
    99: "Lithuania",
    100: "Luxembourg",
    101: "Madagascar",
    102: "Malawi",
    103: "Malaysia",
    104: "Maldives",
    105: "Mali",
    106: "Malta",
    107: "Marshall Islands",
    108: "Mauritania",
    109: "Mauritius",
    110: "Mexico",
    111: "Micronesia, Federated States of...",
    112: "Monaco",
    113: "Mongolia",
    114: "Montenegro",
    115: "Morocco",
    116: "Mozambique",
    117: "Myanmar",
    118: "Namibia",
    119: "Nauru",
    120: "Nepal",
    121: "Netherlands",
    122: "New Zealand",
    123: "Nicaragua",
    124: "Niger",
    125: "Nigeria",
    126: "North Korea",
    127: "Norway",
    128: "Oman",
    129: "Pakistan",
    130: "Palau",
    131: "Panama",
    132: "Papua New Guinea",
    133: "Paraguay",
    134: "Peru",
    135: "Philippines",
    136: "Poland",
    137: "Portugal",
    138: "Qatar",
    139: "Republic of Moldova",
    140: "Romania",
    141: "Russian Federation",
    142: "Rwanda",
    143: "Saint Kitts and Nevis",
    144: "Saint Lucia",
    145: "Saint Vincent and the Grenadines",
    146: "Samoa",
    147: "San Marino",
    148: "Sao Tome and Principe",
    149: "Saudi Arabia",
    150: "Senegal",
    151: "Serbia",
    152: "Seychelles",
    153: "Sierra Leone",
    154: "Singapore",
    155: "Slovakia",
    156: "Slovenia",
    157: "Solomon Islands",
    158: "Somalia",
    159: "South Africa",
    160: "South Korea",
    161: "Spain",
    162: "Sri Lanka",
    163: "Sudan",
    164: "Suriname",
    165: "Swaziland",
    166: "Sweden",
    167: "Switzerland",
    168: "Syrian Arab Republic",
    169: "Tajikistan",
    170: "Thailand",
    171: "The former Yugoslav Republic of Macedonia",
    172: "Timor-Leste",
    173: "Togo",
    174: "Tonga",
    175: "Trinidad and Tobago",
    176: "Tunisia",
    177: "Turkey",
    178: "Turkmenistan",
    179: "Tuvalu",
    180: "Uganda",
    181: "Ukraine",
    182: "United Arab Emirates",
    183: "United Kingdom of Great Britain and Northern Ireland",
    184: "United Republic of Tanzania",
    185: "United States of America",
    186: "Uruguay",
    187: "Uzbekistan",
    188: "Vanuatu",
    189: "Venezuela, Bolivarian Republic of...",
    190: "Viet Nam",
    191: "Yemen",
    192: "Zambia",
    193: "Zimbabwe"
}

states = {
    1: "Alabama",
    2: "Alaska",
    3: "Arizona",
    4: "Arkansas",
    5: "California",
    6: "Colorado",
    7: "Connecticut",
    8: "Delaware",
    9: "District of Columbia",
    10: "Florida",
    11: "Georgia",
    12: "Hawaii",
    13: "Idaho",
    14: "Illinois",
    15: "Indiana",
    16: "Iowa",
    17: "Kansas",
    18: "Kentucky",
    19: "Louisiana",
    20: "Maine",
    21: "Maryland",
    22: "Massachusetts",
    23: "Michigan",
    24: "Minnesota",
    25: "Mississippi",
    26: "Missouri",
    27: "Montana",
    28: "Nebraska",
    29: "Nevada",
    30: "New Hampshire",
    31: "New Jersey",
    32: "New Mexico",
    33: "New York",
    34: "North Carolina",
    35: "North Dakota",
    36: "Ohio",
    37: "Oklahoma",
    38: "Oregon",
    39: "Pennsylvania",
    40: "Puerto Rico",
    41: "Rhode Island",
    42: "South Carolina",
    43: "South Dakota",
    44: "Tennessee",
    45: "Texas",
    46: "Utah",
    47: "Vermont",
    48: "Virginia",
    49: "Washington",
    50: "West Virginia",
    51: "Wisconsin",
    52: "Wyoming",
    53: "I do not reside in the United States"
}

mappings = {
    'gender': {
        1: 'Male',
        2: 'Female',
        3: 'Non-binary / third gender',
        4: 'Prefer not to say'
    },
    'races_1': { 1: 'White or Caucasian' },
    'races_2': { 1: 'Black or African American' },
    'races_3': { 1: 'American Indian/Native American or Alaska Native' },
    'races_4': { 1: 'Asian' },
    'races_5': { 1: 'Native Hawaiian or Other Pacific Islander' },
    'races_6': { 1: 'Other' },
    'races_7': { 1: 'Prefer not to say' },

    'employment_status': {
        1: 'Working full-time',
        2: 'Working part-time',
        3: 'Unemployed and looking for work',
        4: 'A homemaker or stay-at-home parent',
        5: 'Student',
        6: 'Retired',
        7: 'Other'
    },
    'marital_status': {
        1: 'Married',
        2: 'Living with a partner',
        3: 'Widowed',
        4: 'Divorced/Separated',
        5: 'Never been married'
    },
    'household_income': {
        1: 'Less than $25,000',
        2: '$25,000-$49,999',
        3: '$50,000-$74,999',
        4: '$75,000-$99,999',
        5: '$100,000-$149,999',
        6: '$150,000-$199,000',
        7: '$200,000 or more'
    },
    'education_level': {
        1: 'Some high school or less',
        2: 'High school diploma or GED',
        3: 'Some college, but no degree',
        4: 'Associates or technical degree',
        5: 'Bachelor’s degree',
        6: 'Graduate or professional degree (MA, MS, MBA, PhD, JD, MD, DDS etc.)',
        7: 'Prefer not to say'
    },
    'state': states,
    'country': countries,
    'political_orientaton': {
        1: 'Republican',
        2: 'Democrat',
        3: 'Independent',
        5: 'No preference'
    },
    'republican_strength': {
        1: 'Strong',
        2: 'Not very strong'
    },
    'democrat_strength': {
        1: 'Strong',
        2: 'Not very strong'
    },
    'party_alignment': {
        1: 'Republican',
        2: 'Democratic'
    },
    'political_Ideology_1': {
        0: "Decline to specify",
        1: "Extremely Liberal",
        2: "Liberal",
        3: "Moderately Liberal",
        4: "Center",
        5: "Moderately Conservative",
        6: "Conservative",
        7: "Extremely Conservative"
    },
    'voted': {
        1: 'Yes',
        2: 'No'
    },
    'vote_for': {
        1: 'Donald Trump',
        2: 'Kamala Harris'
    },
    'shopping_freq': {
        1: 'Daily',
        2: 'Weekly',
        3: 'Monthly',
        4: 'A few times a year',
        5: 'Rarely or never'
    },
    'monthly_spend': {
        1: 'Less than $50',
        2: '$50 - $100',
        3: '$101 - $250',
        4: '$251 - $500',
        5: 'More than $500'
    },
    'vacation_travel_freq': {
        1: 'Never',
        2: 'Every few years',
        3: 'Once a year',
        4: 'Multiple times a year'
    },
    'brand_importance': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    },
    'brands_type_pref_1': {1: 'Luxury' },
    'brands_type_pref_2': {1: 'Budget-friendly' },
    'brands_type_pref_3': {1: 'Premium' },
    'brands_type_pref_4': {1: 'Sustainable' },
    'brands_type_pref_5': {1: 'Boutique' },
    'brands_type_pref_6': {1: 'Mainstream' },
    'discount_importance': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    },
    'buy_decision_style': {
        1: 'I make quick, spontaneous decisions',
        2: 'I take my time and carefully consider my options'
    },
    'device_used_to_buy_1': { 1: 'Smartphone' },
    'device_used_to_buy_2': { 1: 'Tablet' },
    'device_used_to_buy_3': { 1: 'Laptop' },
    'device_used_to_buy_4': { 1: 'Desktop' },

    'social_m_influence': {
        1: 'Not at all',
        2: 'A little',
        3: 'Somewhat',
        4: 'Quite a bit',
        5: 'Very much'
    },
    'eco_friendly_imp': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    }
}