# mappings.py

COUNTRIES = {
    1: "Afghanistan",
    2: "Albania",
    3: "Algeria",
    4: "Andorra",
    5: "Angola",
    6: "Antigua and Barbuda",
    7: "Argentina",
    8: "Armenia",
    9: "Australia",
    10: "Austria",
    11: "Azerbaijan",
    12: "Bahamas",
    13: "Bahrain",
    14: "Bangladesh",
    15: "Barbados",
    16: "Belarus",
    17: "Belgium",
    18: "Belize",
    19: "Benin",
    20: "Bhutan",
    21: "Bolivia",
    22: "Bosnia and Herzegovina",
    23: "Botswana",
    24: "Brazil",
    25: "Brunei Darussalam",
    26: "Bulgaria",
    27: "Burkina Faso",
    28: "Burundi",
    29: "Cambodia",
    30: "Cameroon",
    31: "Canada",
    32: "Cape Verde",
    33: "Central African Republic",
    34: "Chad",
    35: "Chile",
    36: "China",
    37: "Colombia",
    38: "Comoros",
    39: "Congo, Republic of the...",
    40: "Costa Rica",
    41: "Côte d'Ivoire",
    42: "Croatia",
    43: "Cuba",
    44: "Cyprus",
    45: "Czech Republic",
    46: "Democratic Republic of the Congo",
    47: "Denmark",
    48: "Djibouti",
    49: "Dominica",
    50: "Dominican Republic",
    51: "Ecuador",
    52: "Egypt",
    53: "El Salvador",
    54: "Equatorial Guinea",
    55: "Eritrea",
    56: "Estonia",
    57: "Ethiopia",
    58: "Fiji",
    59: "Finland",
    60: "France",
    61: "Gabon",
    62: "Gambia",
    63: "Georgia",
    64: "Germany",
    65: "Ghana",
    66: "Greece",
    67: "Grenada",
    68: "Guatemala",
    69: "Guinea",
    70: "Guinea-Bissau",
    71: "Guyana",
    72: "Haiti",
    73: "Honduras",
    74: "Hong Kong (S.A.R.)",
    75: "Hungary",
    76: "Iceland",
    77: "India",
    78: "Indonesia",
    79: "Iran",
    80: "Iraq",
    81: "Ireland",
    82: "Israel",
    83: "Italy",
    84: "Jamaica",
    85: "Japan",
    86: "Jordan",
    87: "Kazakhstan",
    88: "Kenya",
    89: "Kiribati",
    90: "Kuwait",
    91: "Kyrgyzstan",
    92: "Lao People's Democratic Republic",
    93: "Latvia",
    94: "Lebanon",
    95: "Lesotho",
    96: "Liberia",
    97: "Libyan Arab Jamahiriya",
    98: "Liechtenstein",
    99: "Lithuania",
    100: "Luxembourg",
    101: "Madagascar",
    102: "Malawi",
    103: "Malaysia",
    104: "Maldives",
    105: "Mali",
    106: "Malta",
    107: "Marshall Islands",
    108: "Mauritania",
    109: "Mauritius",
    110: "Mexico",
    111: "Micronesia, Federated States of...",
    112: "Monaco",
    113: "Mongolia",
    114: "Montenegro",
    115: "Morocco",
    116: "Mozambique",
    117: "Myanmar",
    118: "Namibia",
    119: "Nauru",
    120: "Nepal",
    121: "Netherlands",
    122: "New Zealand",
    123: "Nicaragua",
    124: "Niger",
    125: "Nigeria",
    126: "North Korea",
    127: "Norway",
    128: "Oman",
    129: "Pakistan",
    130: "Palau",
    131: "Panama",
    132: "Papua New Guinea",
    133: "Paraguay",
    134: "Peru",
    135: "Philippines",
    136: "Poland",
    137: "Portugal",
    138: "Qatar",
    139: "Republic of Moldova",
    140: "Romania",
    141: "Russian Federation",
    142: "Rwanda",
    143: "Saint Kitts and Nevis",
    144: "Saint Lucia",
    145: "Saint Vincent and the Grenadines",
    146: "Samoa",
    147: "San Marino",
    148: "Sao Tome and Principe",
    149: "Saudi Arabia",
    150: "Senegal",
    151: "Serbia",
    152: "Seychelles",
    153: "Sierra Leone",
    154: "Singapore",
    155: "Slovakia",
    156: "Slovenia",
    157: "Solomon Islands",
    158: "Somalia",
    159: "South Africa",
    160: "South Korea",
    161: "Spain",
    162: "Sri Lanka",
    163: "Sudan",
    164: "Suriname",
    165: "Swaziland",
    166: "Sweden",
    167: "Switzerland",
    168: "Syrian Arab Republic",
    169: "Tajikistan",
    170: "Thailand",
    171: "The former Yugoslav Republic of Macedonia",
    172: "Timor-Leste",
    173: "Togo",
    174: "Tonga",
    175: "Trinidad and Tobago",
    176: "Tunisia",
    177: "Turkey",
    178: "Turkmenistan",
    179: "Tuvalu",
    180: "Uganda",
    181: "Ukraine",
    182: "United Arab Emirates",
    183: "United Kingdom of Great Britain and Northern Ireland",
    184: "United Republic of Tanzania",
    185: "United States of America",
    186: "Uruguay",
    187: "Uzbekistan",
    188: "Vanuatu",
    189: "Venezuela, Bolivarian Republic of...",
    190: "Viet Nam",
    191: "Yemen",
    192: "Zambia",
    193: "Zimbabwe"
}

STATES = {
    1: "Alabama",
    2: "Alaska",
    3: "Arizona",
    4: "Arkansas",
    5: "California",
    6: "Colorado",
    7: "Connecticut",
    8: "Delaware",
    9: "District of Columbia",
    10: "Florida",
    11: "Georgia",
    12: "Hawaii",
    13: "Idaho",
    14: "Illinois",
    15: "Indiana",
    16: "Iowa",
    17: "Kansas",
    18: "Kentucky",
    19: "Louisiana",
    20: "Maine",
    21: "Maryland",
    22: "Massachusetts",
    23: "Michigan",
    24: "Minnesota",
    25: "Mississippi",
    26: "Missouri",
    27: "Montana",
    28: "Nebraska",
    29: "Nevada",
    30: "New Hampshire",
    31: "New Jersey",
    32: "New Mexico",
    33: "New York",
    34: "North Carolina",
    35: "North Dakota",
    36: "Ohio",
    37: "Oklahoma",
    38: "Oregon",
    39: "Pennsylvania",
    40: "Puerto Rico",
    41: "Rhode Island",
    42: "South Carolina",
    43: "South Dakota",
    44: "Tennessee",
    45: "Texas",
    46: "Utah",
    47: "Vermont",
    48: "Virginia",
    49: "Washington",
    50: "West Virginia",
    51: "Wisconsin",
    52: "Wyoming",
    53: "I do not reside in the United States"
}

MAPPINGS = {
    'gender': {
        1: 'Male',
        2: 'Female',
        3: 'Non-binary / third gender',
        4: 'Prefer not to say'
    },
    'races_1': { 1: 'White or Caucasian' },
    'races_2': { 1: 'Black or African American' },
    'races_3': { 1: 'American Indian/Native American or Alaska Native' },
    'races_4': { 1: 'Asian' },
    'races_5': { 1: 'Native Hawaiian or Other Pacific Islander' },
    'races_6': { 1: 'Other' },
    'races_7': { 1: 'Prefer not to say' },

    'employment_status': {
        1: 'Working full-time',
        2: 'Working part-time',
        3: 'Unemployed and looking for work',
        4: 'A homemaker or stay-at-home parent',
        5: 'Student',
        6: 'Retired',
        7: 'Other'
    },
    'marital_status': {
        1: 'Married',
        2: 'Living with a partner',
        3: 'Widowed',
        4: 'Divorced/Separated',
        5: 'Never been married'
    },
    'household_income': {
        1: 'Less than $25,000',
        2: '$25,000-$49,999',
        3: '$50,000-$74,999',
        4: '$75,000-$99,999',
        5: '$100,000-$149,999',
        6: '$150,000-$199,000',
        7: '$200,000 or more'
    },
    'education_level': {
        1: 'Some high school or less',
        2: 'High school diploma or GED',
        3: 'Some college, but no degree',
        4: 'Associates or technical degree',
        5: 'Bachelor’s degree',
        6: 'Graduate or professional degree (MA, MS, MBA, PhD, JD, MD, DDS etc.)',
        7: 'Prefer not to say'
    },
    'state': STATES,
    'country': COUNTRIES,
    'political_orientaton': {
        1: 'Republican',
        2: 'Democrat',
        3: 'Independent',
        5: 'No preference'
    },
    'republican_strength': {
        1: 'Strong',
        2: 'Not very strong'
    },
    'democrat_strength': {
        1: 'Strong',
        2: 'Not very strong'
    },
    'party_alignment': {
        1: 'Republican',
        2: 'Democratic'
    },
    'political_Ideology_1': {
        0: "Decline to specify",
        1: "Extremely Liberal",
        2: "Liberal",
        3: "Moderately Liberal",
        4: "Center",
        5: "Moderately Conservative",
        6: "Conservative",
        7: "Extremely Conservative"
    },
    'voted': {
        1: 'Yes',
        2: 'No'
    },
    'vote_for': {
        1: 'Donald Trump',
        2: 'Kamala Harris'
    },
    'shopping_freq': {
        1: 'Daily',
        2: 'Weekly',
        3: 'Monthly',
        4: 'A few times a year',
        5: 'Rarely or never'
    },
    'monthly_spend': {
        1: 'Less than $50',
        2: '$50 - $100',
        3: '$101 - $250',
        4: '$251 - $500',
        5: 'More than $500'
    },
    'vacation_travel_freq': {
        1: 'Never',
        2: 'Every few years',
        3: 'Once a year',
        4: 'Multiple times a year'
    },
    'brand_importance': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    },
    'brands_type_pref_1': {1: 'Luxury' },
    'brands_type_pref_2': {1: 'Budget-friendly' },
    'brands_type_pref_3': {1: 'Premium' },
    'brands_type_pref_4': {1: 'Sustainable' },
    'brands_type_pref_5': {1: 'Boutique' },
    'brands_type_pref_6': {1: 'Mainstream' },
    'discount_importance': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    },
    'buy_decision_style': {
        1: 'I make quick, spontaneous decisions',
        2: 'I take my time and carefully consider my options'
    },
    'device_used_to_buy_1': { 1: 'Smartphone' },
    'device_used_to_buy_2': { 1: 'Tablet' },
    'device_used_to_buy_3': { 1: 'Laptop' },
    'device_used_to_buy_4': { 1: 'Desktop' },

    'social_m_influence': {
        1: 'Not at all',
        2: 'A little',
        3: 'Somewhat',
        4: 'Quite a bit',
        5: 'Very much'
    },
    'eco_friendly_imp': {
        1: 'Not at all important',
        2: 'Slightly important',
        3: 'Moderately important',
        4: 'Important',
        5: 'Very important'
    }
}

# Product evaluation statements
STATEMENTS = [
    "I find this product advertisement to be persuasive.",
    "This is an effective advertisement.",
    "I would purchase this product after seeing this advertisement.",
    "Overall, I like this product advertisement.",
    "This advertisement has made me more interested in the product.",
    "I am interested in learning more about this product after seeing this advertisement."
]

# Product 1 Descriptions per trait
TRAIT_PRODUCT_DESCRIPTIONS_1 = {
    "openness": "Designed for visionaries who appreciate iconic design innovation. The signature parallel grooves, inspired by early aviation, transform aluminum into flowing sculptural lines. The 35L design challenges you to curate essentials like a minimalist art piece. Each element tells a story - from the understated RIMOWA lettering to the precisely engineered corners. The multi-directional wheels move like brush strokes, while the anodized surface creates ever-changing light plays. Perfect for creative minds who see beauty in engineering.",
    "consc": "Exemplifies German engineering precision at its finest. Each of the 15 parallel grooves is exactly 14mm apart, providing optimal structural integrity while reducing weight by 26%. The aircraft-grade aluminum body offers a precise 35L capacity, optimized for carry-on efficiency. The TSA-approved locks feature 1,000 unique combinations, while the whisper-quiet wheels are tested for 832,000 rotations. The interior features a calibrated 50/50 split. Every measurement, every component is exactingly calculated.",
    "extr": "Turns heads and starts conversations wherever you go. Its iconic grooved design and gleaming aluminum finish make an unforgettable entrance in any setting. The sleek 35L profile is perfect for spontaneous weekend getaways or high-impact business trips. The distinctive silhouette has graced more Instagram stories than any luxury luggage, while the characteristic wheel sound announces your arrival with style. Each scratch tells a story of your adventures. Travel as the trendsetter you are.",
    "agree": "Embodies our commitment to responsible luxury and mindful travel. Our sustainable process uses recycled aluminum for the 35L design, crafted by artisans earning fair wages in family-owned facilities. The smooth-gliding wheels and ergonomic handle are designed with consideration for fellow travelers. We've partnered with global repair artisans to ensure local maintenance, supporting communities worldwide. Join a movement of conscious travelers who believe luxury should lift everyone up.",
    "neuro": "Eliminates travel worries through multiple protection layers. The 35L aircraft-grade aluminum shell, reinforced with 12 structural grooves, exceeds military impact standards while ensuring carry-on compliance. Our corner guards provide eight-point drop protection, with a watertight seal system for all weather. Dual TSA locks feature tamper-alert technology and embedded tracking for real-time location. The stabilized wheel system prevents tip-overs. Travel with absolute confidence."
}

# Product 2 Descriptions per trait
TRAIT_PRODUCT_DESCRIPTIONS_2 = {
    "openness": "Discover a revolutionary art form in travel organization with RIMOWA's visionary cubes. Like modernist sculpture, their fluid compression transforms space itself, challenging conventional boundaries. Each cube is a canvas of infinite possibilities, crafted from aerospace-inspired recycled materials. The avant-garde design morphs as you pack, creating dynamic spatial compositions. Perfect for creative pioneers who see packing as performance art. Break free from ordinary constraints and curate your journey like a gallery installation. Transform travel into pure innovation",
    "consc": "Experience the pinnacle of German precision with RIMOWA's meticulously engineered packing system. Each cube reduces volume by 35% while maintaining perfect structural integrity. The design includes precise compression markers, reinforced stress points tested to 12kg capacity, and premium YKK zippers rated for 35,000 cycles. The systematic organization maximizes your 35L cabin case space with efficient compartmentalization. Achieve flawless organization with engineering excellence, measured and tested to perfection.",
    "extr": "Become the star of every destination with RIMOWA's most viral travel innovation. These show-stopping cubes have sparked over 350M views across social media, dominated Instagram reels, and inspired countless #PackingWithRIMOWA moments worldwide. The intelligent compression system leaves room for spontaneous shopping discoveries and outfit changes. Their ultra-sleek design transforms hotel room unpacking into a content creator's dream. Perfect for jet-setters who collect likes as often as passport stamps. Pack to impress, travel to be seen.",
    "agree": "Join RIMOWA's global family of mindful travelers with our most conscientious creation yet. Each cube supports three local artisan communities and is crafted from ocean-recovered materials, preventing 12 plastic bottles from harming marine life. The collaborative design promotes shared packing experiences, while our fair-trade manufacturing empowers developing communities. Every purchase funds environmental restoration and educational initiatives. Travel with compassion, pack with purpose, share with love.",
    "neuro": "Achieve complete travel peace of mind with RIMOWA's most secure packing innovation. Features military-grade compression technology, antimicrobial Polygiene® treatment, and our patented triple-lock zipper system. Built-in stress indicators prevent over-compression, while RFID-traceable markers ensure nothing gets lost. The water-resistant barriers exceed IP67 standards, protecting from all environmental risks. Backed by our lifetime guarantee and 24/7 global support network. Transform uncertainty into absolute confidence."
}

# Product 3 Descriptions per trait
TRAIT_PRODUCT_DESCRIPTIONS_3 = {
    "openness": "Discover a sensory revolution in hydration with 24Bottles' artistic innovation. The Clima bottle is a modernist sculpture in stainless steel, featuring avant-garde temperature control that maintains cold for 24 hours or heat for 12. Each bottle's minimalist silhouette and custom-curated colors challenge conventional design boundaries. Perfect for creative spirits who see everyday objects as art pieces, this bottle transforms hydration into a statement of individual expression. Embrace innovation in every sip.",
    "consc": "Master your hydration with 24Bottles' precision-engineered Clima bottle. Features 316-grade stainless steel construction, maintaining exact temperatures (24 hours cold/12 hours hot) with 99.9% efficiency. The leak-proof cap system withstands 20,000+ open-close cycles, while the 1L capacity optimizes daily water intake requirements. Each bottle saves 0.08kg carbon footprint daily versus disposable alternatives. Achieve perfect hydration with Swiss-tested temperature control and German-engineered durability.",
    "extr": "Make every sip an opportunity with 24Bottles' most sociable hydration companion. The Clima bottle naturally starts conversations, whether you're at the office, gym, traveling, or meeting friends. Its distinctive design and premium finish draw admiring glances, while double-wall insulation keeps drinks cold for 24 hours or hot for 12 - perfect for impromptu coffee dates or extended adventures with friends. Ideal for those who love bringing people together and staying energized through every social moment. Turn every drink into a chance to connect.",
    "agree": "Join 24Bottles' compassionate hydration movement with the eco-conscious Clima bottle. Each purchase prevents 580 single-use plastics annually and supports global water conservation projects. Crafted through fair-labor practices, this bottle embodies our commitment to environmental harmony. The mindful design keeps drinks cold for 24 hours or hot for 12, while supporting clean water initiatives worldwide. Choose sustainable hydration that nurtures both people and planet. Every sip makes a difference.",
    "neuro": "Experience worry-free hydration with 24Bottles' most secure temperature-control innovation. The Clima bottle features antimicrobial coating, triple-sealed cap technology, and certified food-grade steel construction. Advanced vacuum insulation guarantees temperature stability (24 hours cold/12 hours hot), while the non-slip texture prevents accidents. Each bottle undergoes 25-point safety testing and includes our lifetime warranty. Stay perfectly hydrated while enjoying complete peace of mind."
}

# Trait descriptions dictionary for all products
TRAIT_PRODUCT_DESCRIPTIONS = {
    1: TRAIT_PRODUCT_DESCRIPTIONS_1,
    2: TRAIT_PRODUCT_DESCRIPTIONS_2,
    3: TRAIT_PRODUCT_DESCRIPTIONS_3
}

PRODUCT_TITLES = {
    1: "The RIMOWA Original",
    2: "Compressible Packing Cubes",
    3: "Clima Water Bottle"
}

IMAGE_UUIDS = {
    1: ['4f41ad44-6472-4403-8e59-0fb0e5eca575', 'e30bbefa-b135-4a46-bf32-ed9437be8733', 'a56079a4-1f50-4019-9344-947101bd3e4b'],
    2: ['7c046f64-1209-447d-a68a-b984f3508e0b', '82ffd7a6-87dc-4365-9c9f-2e76263908be', '851dedbe-3b32-45ca-8c32-4ddc510f7327'],
    3: ['2a81aec9-c164-4d29-9281-360547f04ac4', 'd34d3ec1-073d-45b9-baca-a0d3411e9e0c', 'ff0ab897-50b8-458e-bfa5-7550b8a48648']
}